#!/usr/bin/env ruby

libx = File.expand_path("../lib", __FILE__)
$LOAD_PATH.unshift(libx) unless $LOAD_PATH.include?(libx)

day = ARGV.shift

if day.nil?
  $stderr.puts "Usage: #{File.basename($0)} <day(1..25)>"
  exit 1
end

day  = day.to_i
name = 'day%02i' % [day]

begin
  require name
  klass = Kernel.const_get(name.capitalize)
  klass.new("input/#{name}.txt").display
rescue LoadError => exception
  puts 'Day %02i not yet implemented!' % [day]
end
